---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ethereum-sepolia-cert
spec:
  secretName: ethereum-sepolia-tls

  dnsNames:
    - sepolia.ethereum.iosis.tech
  issuerRef:
    name: letsencrypt-http01
    kind: Issuer