services:
  reth:
    restart: unless-stopped
    image: ghcr.io/paradigmxyz/reth
    ports:
      - '9001:9001' # metrics
      - '30303:30303' # eth/66 peering
      - '8545:8545' # rpc
      - '8551:8551' # engine
    volumes:
      - ./mainnet_data:/root/.local/share/reth/mainnet
      - ./logs:/root/logs
      - ./jwttoken:/root/jwt:ro
    # https://paradigmxyz.github.io/reth/run/troubleshooting.html#concurrent-database-access-error-using-containersdocker
    pid: host
    # For Sepolia, replace `--chain mainnet` with `--chain sepolia`
    command: >
      node
      --chain mainnet
      --metrics 0.0.0.0:9001
      --log.file.directory /root/logs
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /root/jwt/jwt.hex
      --http --http.addr 0.0.0.0 --http.port 8545
      --http.api "eth,net,web3"

  lighthouse:
    restart: unless-stopped
    image: sigp/lighthouse:v5.1.3-modern
    depends_on:
      - reth
    ports:
      - '5052:5052/tcp' # rpc
      - '5053:5053/tcp'
      - '5054:5054/tcp' # metrics
      - '9000:9000/tcp' # p2p
      - '9000:9000/udp' # p2p
    volumes:
      - ./lighthousedata:/root/.lighthouse
      - ./jwttoken:/root/jwt:ro
    # For Sepolia:
    # - Replace `--network mainnet` with `--network sepolia`
    # - Use different checkpoint sync URL: `--checkpoint-sync-url https://sepolia.checkpoint-sync.ethpandaops.io`
    command: >
      lighthouse bn
      --network mainnet
      --http --http-address 0.0.0.0
      --execution-endpoint http://reth:8551
      --metrics --metrics-address 0.0.0.0
      --execution-jwt /root/jwt/jwt.hex
      --checkpoint-sync-url https://mainnet.checkpoint.sigp.io