apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      initContainers:
      - name: init-jwt
        image: busybox
        command: ['sh', '-c', 'echo $JWT > /data/jwt.txt']
        env:
        - name: JWT
          valueFrom:
            secretKeyRef:
              name: ethereum-secret
              key: JWT
        volumeMounts:
        - name: geth-data
          mountPath: /data/
      containers:
      - name: geth
        image: ethereum/client-go
        command: ["geth"]
        args:
        - "--sepolia"
        - "--syncmode"
        - "full"
        - "--gcmode"
        - "archive"
        - "--datadir"
        - "/data/geth/"
        - "--authrpc.addr"
        - "0.0.0.0"
        - "--authrpc.port"
        - "8545"
        - "--authrpc.vhosts"
        - "*"
        - "--authrpc.jwtsecret"
        - "/data/jwt.txt"
        - "--http"
        - "--http.addr"
        - "0.0.0.0"
        - "--http.port"
        - "3334"
        - "--http.api"
        - "eth,net,web3"
        - "--http.corsdomain=*"
        - "--http.vhosts=*"
        ports:
        - containerPort: 3334
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 8547
        - containerPort: 30303
        volumeMounts:
        - name: geth-data
          mountPath: /data/
      volumes:
      - name: geth-data
        persistentVolumeClaim:
          claimName: geth-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: geth-svc
  annotations:
    kube-vip.io/loadbalancerIPs: "0.0.0.0"
    kube-vip.io/hwaddr: "00:00:6C:32:98:81"
    kube-vip.io/loadbalancerHostname: "sepolia-ethereum-node"
spec:
  ports:
  - port: 3334
    targetPort: 3334
    protocol: TCP
    name: http-ws-public-api
  - port: 8545
    targetPort: 8545
    protocol: TCP
    name: http-json-rpc-api
  - port: 8546
    targetPort: 8546
    protocol: TCP
    name: websocket-json-rpc-api
  - port: 8547
    targetPort: 8547
    protocol: TCP
    name: graphql-api
  - port: 30303
    targetPort: 30303
    protocol: TCP
    name: tcp-p2p
  - port: 30303
    targetPort: 30303
    protocol: UDP
    name: udp-p2p
  selector:
    app: geth
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geth-ingress
  annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 0
      nginx.org/websocket-services: "geth-svc"
spec:
  ingressClassName: nginx-ingress-prod
  tls:
    - hosts:
        - sepolia.ethereum.iosis.tech
        - ws.sepolia.ethereum.iosis.tech
      secretName: ethereum-sepolia-tls
  rules:
    - host: sepolia.ethereum.iosis.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geth-svc
                port:
                  number: 3334
    - host: ws.sepolia.ethereum.iosis.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geth-svc
                port:
                  number: 3334