apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iosis-tech-sepolia-ethereum-node

resources:
  - deployment-geth.yaml
  - deployment-lighthouse.yaml
  - certificates.yaml
  - issuer.yaml
  - pvc.yaml

secretGenerator:
  - name: jwt-secret
    envs:
      - secret.env
    options:
      disableNameSuffixHash: true