apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iosis-tech-mainnet-ethereum

resources:
  - deployment-geth.yaml
  - deployment-lighthouse.yaml
  - certificates.yaml
  - issuer.yaml
  # - pvc.yaml

secretGenerator:
  - name: ethereum-secret
    envs:
      - secret.env
    options:
      disableNameSuffixHash: true