apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-pvc
spec:
  storageClassName: topolvm-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Gi